language: php

php:
  - 8.0
  - 8.1

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=phpcs.xml src
  - ./vendor/bin/phpstan --level=0 --no-progress analyse src